3ª Prova/Apicultura/Apicultura/urls.py
from django.contrib import admin
from django.urls import path, include
from Producao.views import pagina_principal
from Producao.views import login_view

"""urlpatterns = [
    path('admin/', admin.site.urls),
]"""

urlpatterns = [
    path('pagina_principal', pagina_principal, name='pagina_principal'),
    path('admin/', admin.site.urls),
    path('Producao/', include('Producao.urls', namespace='Producao')),
    path('', login_view, name='login'),
]



3ª Prova/Apicultura/Producao/urls.py
from django.urls import path
from Producao import views



app_name = 'Producao'

urlpatterns = [
    path('criar-criacao/', views.criar_criacao, name='criar_criacao'),
    path('listar-criacao/', views.listar_criacao, name='listar_criacao'),
    path('detalhes-criacao/<int:criacao_id>/', views.detalhes_criacao, name='detalhes_criacao'),
    path('criacao-editar/<int:criacao_id>/', views.editar_criacao, name='editar_criacao'),
    path('criar-coleta/', views.criar_coleta, name='criar_coleta'),
    path('listar-coletas/', views.listar_coletas, name='listar_coletas'),
    path('detalhes-coleta/<int:coleta_id>/', views.detalhes_coleta, name='detalhes_coleta'),
    path('coleta-editar/<int:coleta_id>/', views.editar_coleta, name='editar_coleta'),
    path('coleta-deletar/<int:coleta_id>/', views.deletar_coleta, name='deletar_coleta'),
    path('relatorio/', views.relatorio_coleta, name='relatorio_coleta'),
    path('', views.pagina_principal, name='pagina_principal'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

3ª Prova/Apicultura/Producao/models.py
from django.db import models

class Criacao(models.Model):
    raca = models.CharField(max_length=50, verbose_name='Raça')
    data_entrada = models.DateField(verbose_name='Data de Entrada')

    def __str__(self):
        return str(self.data_entrada) + ", " + str(self.raca)

    class Meta:
        ordering = ['-data_entrada']


class Coleta(models.Model):
    criacao = models.ForeignKey(Criacao, on_delete=models.CASCADE, verbose_name='Criação')
    data = models.DateField(verbose_name='Data')
    quantidade = models.IntegerField(verbose_name='Quantidade')

    def _str_(self):
        return self.data

    class Meta:
        ordering = ['-data']

3ª Prova/Apicultura/Producao/forms.py
from django import forms
from Producao.models import Criacao, Coleta
from django.utils import timezone

class ColetaForm(forms.Form):
    criacao = forms.ModelChoiceField(queryset=Criacao.objects.all())

class CriacaoForm(forms.ModelForm):
    class Meta:
        model = Criacao
        fields = ['raca', 'data_entrada']

    def clean_data_entrada(self):
        data_entrada = self.cleaned_data.get('data_entrada')
        if data_entrada and data_entrada > timezone.now().date():
            raise forms.ValidationError("Não é possivel cadastrar criações com datas futuras.")
        return data_entrada


class ColetaForm(forms.ModelForm):
    class Meta:
        model = Coleta
        fields = ['criacao', 'data', 'quantidade']

    def clean(self):
        cleaned_data = super().clean()
        data = cleaned_data.get('data')
        criacao = cleaned_data.get('criacao')
        if Coleta.objects.filter(criacao=criacao, data=data).exists():
            self.add_error('data', 'Já existe uma coleta registrada com a mesma data para essa criação.')

    def clean_data(self):
        data = self.cleaned_data.get('data')
        if data and data > timezone.now().date():
            raise forms.ValidationError("Não é possivel cadastrar coletas com datas futuras.")
        return data

3ª Prova/Apicultura/Producao/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Criacao, Coleta
from .forms import CriacaoForm, ColetaForm
from django.db.models import Sum
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('Producao:pagina_principal')
        else:
            messages.error(request, 'Credenciais inválidas. Tente novamente.')

    return render(request, 'producao/login.html')


def logout_view(request):
    logout(request)
    return redirect('login')


def listar_criacao(request):
    lista_criacao = Criacao.objects.all()
    return render(request, 'producao/listar_criacao.html', {'lista_criacao': lista_criacao})

@login_required
def criar_criacao(request):
    if request.method == 'POST':
        form = CriacaoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Producao:listar_criacao')
    else:
        form = CriacaoForm()
    return render(request, 'producao/criar_criacao.html', {'form': form})


@login_required
def detalhes_criacao(request, criacao_id):
    criacao = get_object_or_404(Criacao, pk=criacao_id)
    return render(request, 'producao/detalhes_criacao.html', {'criacao': criacao})


@login_required
def editar_criacao(request, criacao_id):
    criacao = get_object_or_404(Criacao, pk=criacao_id)
    if request.method == 'POST':
        form = CriacaoForm(request.POST, instance=criacao)
        if form.is_valid():
            form.save()
            return redirect('Producao:listar_criacao')
    else:
        form = CriacaoForm(instance=criacao)
    return render(request, 'producao/editar_criacao.html', {'form': form, 'criacao': criacao})



def criar_coleta(request):
    if request.method == 'POST':
        form = ColetaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Producao:listar_coletas')
    else:
        form = ColetaForm()
    return render(request, 'producao/criar_coleta.html', {'form': form})

@login_required
def listar_coletas(request):
    lista_coletas = Coleta.objects.all()
    return render(request, 'producao/listar_coleta.html', {'lista_coletas': lista_coletas})


@login_required
def detalhes_coleta(request, coleta_id):
    coleta = get_object_or_404(Coleta, pk=coleta_id)
    return render(request, 'producao/detalhes_coleta.html', {'coleta': coleta})



def editar_coleta(request, coleta_id):
    coleta = get_object_or_404(Coleta, pk=coleta_id)
    if request.method == 'POST':
        form = ColetaForm(request.POST, instance=coleta)
        if form.is_valid():
            form.save()
            return redirect('Producao:listar_coletas')
    else:
        form = ColetaForm(instance=coleta)
    return render(request, 'producao/editar_coleta.html', {'form': form, 'coleta': coleta})


@login_required
def deletar_coleta(request, coleta_id):
    coleta = get_object_or_404(Coleta, pk=coleta_id)

    if request.method == 'POST':
        confirmacao = request.POST.get('confirmacao')

        if confirmacao == 'Excluir':
            coleta.delete()
            return redirect('Producao:listar_coletas')
        else:
            return redirect('Producao:listar_coletas')

    return render(request, 'Producao/deletar_coleta.html', {'coleta': coleta})


def relatorio_coleta(request):
    data_atual = datetime.now().date()

    data_inicio = data_atual - timedelta(days=365)

    coletas = Coleta.objects.filter(data__range=[data_inicio, data_atual])

    resultado = coletas.values('data__month').annotate(soma_quantidade=Sum('quantidade'))

    relatorio = []
    for item in resultado:
        mes = item['data__month']
        quantidade = item['soma_quantidade']
        relatorio.append({'mes': mes, 'quantidade': quantidade})

    context = {
        'relatorio': relatorio
    }

    return render(request, 'producao/relatorio_coleta.html', context)

@login_required
def pagina_principal(request):
    return render(request, 'base.html')

3ª Prova/Apicultura/Producao/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apicultura</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

</head>
<body>

    <div class="container">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'pagina_principal' %}">SApicultura</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Producao:criar_criacao' %}">Criar criações</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Producao:listar_criacao' %}">Listar Criações</a>
                </li>
                <li class= "nav-item">
                   <a class="nav-link" href="{% url 'Producao:criar_coleta' %}">Criar Coletas</a>
                </li>
                <li class= "nav-item">
                    <a class="nav-link" href="{% url 'Producao:listar_coletas' %}">Listar Coletas</a>
                </li>
                 <li class= "nav-item">
                    <a class="nav-link" href="{% url 'Producao:relatorio_coleta' %}">Relatório de Coletas</a>
                </li>
                 <li class= "nav-item">
                    <a class="nav-link" href="{% url 'Producao:logout' %}">LOGOUT</a>
                </li>
                </ul>
            </div>
            </div>
        </nav>

        <h1>Sistema de Apicultura</h1>

        <h4>
            {% block subtitulo %}

            {% endblock %}
        </h4>

        {% block conteudo %}
           <h4>Bem vindo ao sistema de apicultura</h4>
        {% endblock %}

        <h6>
            {% block rodape %}

            {% endblock %}
        </h6>
    </div>
</body>
</html>

3ª Prova/Apicultura/Producao/templates/producao/criar_coleta.html
{% extends "base.html" %}

{% block subtitulo %}
Criar coletas
{% endblock %}

{% block conteudo %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Cadastrar" id="submit_button">
    </form>

{% endblock %}

{% block rodape %}
Bem vindo ao sistema de apicultura
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/criar_criacao.html
{% extends "base.html" %}

{% block subtitulo %}
Criar criacao
{% endblock %}

{% block conteudo %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Cadastrar" id="submit_button">
    </form>

{% endblock %}

{% block rodape %}
Bem vindo ao sistema de apicultura
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/deletar_coleta.html
{% extends 'base.html' %}

{% block conteudo %}
  <h1>Deletar Coleta</h1>
  <p>Você está prestes a deletar a seguinte coleta:</p>
  <p>Criação: {{ coleta.criacao }}</p>
  <p>Data: {{ coleta.data }}</p>
  <p>Quantidade: {{ coleta.quantidade }}</p>

  <p>Deseja continuar com a exclusão?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" name="confirmacao" value="Excluir">
    <input type="submit" name="confirmacao" value="Cancelar">
  </form>
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/detalhes_coleta.html
{% extends "base.html" %}

{% block subtitulo %}
Detalhes da Coleta
{% endblock %}

{% block conteudo %}

<h3>Informações da Coleta</h3>
<p>ID: {{ coleta.id }}</p>
<p>Criação: {{ coleta.criacao.id }}</p>
<p>Data: {{ coleta.data }}</p>
<p>Quantidade: {{ coleta.quantidade }}</p>

<a class="btn btn-primary" href="{% url 'Producao:editar_coleta' coleta_id=coleta.pk %}">Editar</a>
<a class="btn btn-danger" href="{% url 'Producao:deletar_coleta' coleta_id=coleta.pk %}">Deletar</a>

<a href="{% url 'Producao:listar_coletas' %}">Voltar para a lista de coletas</a>

{% endblock %}

{% block rodape %}
Bem-vindo ao sistema de apicultura
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/detalhes_criacao.html
{% extends "base.html" %}

{% block subtitulo %}
Detalhes da Criação
{% endblock %}

{% block conteudo %}

<h3>Informações da Criação</h3>
<p>ID: {{ criacao.id }}</p>
<p>Raça: {{ criacao.raca }}</p>
<p>Data de Entrada: {{ criacao.data_entrada }}</p>

<a class="btn btn-primary" href="{% url 'Producao:editar_criacao' criacao_id=criacao.id %}">Editar</a>
<a href="{% url 'Producao:listar_criacao' %}">Voltar para a lista de criações</a>

{% endblock %}

{% block rodape %}
Bem-vindo ao sistema de apicultura
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/editar_coleta.html
{{% extends "base.html" %}

{% block title %}
Editar Coleta
{% endblock %}

{% block conteudo %}
  <h1>Editar Coleta</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
  </form>
  <a href="{% url 'Producao:listar_coletas' %}">Voltar para a lista de coletas</a>
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/editar_criacao.html
{{% extends "base.html" %}

{% block title %}
Editar Criação
{% endblock %}

{% block conteudo %}
  <h1>Editar Criação</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
  </form>
  <a href="{% url 'Producao:listar_criacao' %}">Voltar para a lista de criações</a>
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/listar_coleta.html
{% extends "base.html" %}

{% block subtitulo %}
Lista de coletas
{% endblock %}

{% block conteudo %}

<strong>{{lista_coletas|length}} Coletas </strong>
    {% for coleta in lista_coletas  %}
        <p id="id_{{coleta.criacao}}_{{coleta.data}}_{{coleta.quantidade}}">{{coleta}}
            <a id="id_button_{{criacao.pk}}" class="btn btn-success" href="{% url 'Producao:detalhes_coleta' coleta_id=coleta.pk %}">Detalhes</a>
        </p>


    {% endfor %}

{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/listar_criacao.html
{% extends "base.html" %}

{% block subtitulo %}
Lista de criações
{% endblock %}

{% block conteudo %}

<strong>{{lista_criacao|length}} Criacoes </strong>
    {% for criacao in lista_criacao  %}
        <p id="id_{{criacao.raca}}_{{criacao.data_entrada}}">{{criacao}}
            <a id="id_button_{{criacao.pk}}" class="btn btn-success" href="{% url 'Producao:detalhes_criacao' criacao_id=criacao.pk %}">Detalhes</a>
        </p>
    {% endfor %}

{% endblock %}

{% block rodape %}
Bem vindo ao sistema de apicultura
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/login.html
{% extends 'base.html' %}

{% block conteudo %}
  <h2>Login</h2>
  {% if messages %}
    {% for message in messages %}
      <div>{{ message }}</div>
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="username">Usuário:</label>
    <input type="text" id="username" name="username" required><br>
    <label for="password">Senha:</label>
    <input type="password" id="password" name="password" required><br>
    <input type="submit" value="Login">
  </form>
{% endblock %}

3ª Prova/Apicultura/Producao/templates/producao/relatorio_coleta.html
{% extends "base.html" %}

{% block subtitulo %}
Relatório de Coleta
{% endblock %}

{% block conteudo %}
<h3>Soma da Quantidade Coletada por Mês nos Últimos 12 Meses:</h3>
<table class="table">
    <thead>
        <tr>
            <th>Mês</th>
            <th>Quantidade</th>
        </tr>
    </thead>
    <tbody>
        {% for item in relatorio %}
        <tr>
            <td>{{ item.mes }}</td>
            <td>{{ item.quantidade }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}